title:		"OS211"
author:     "Asfiolitha Wilmarani"
urlweb:     "https://asfiowilma.github.io/os211"
urlgithub:      "https://github.com/asfiowilma/os211"
urlghpage:      "https://asfiowilma.github.io/os211"
mygithub:       "https://github.com/asfiowilma"
sitemap:        "true"
